### PR TITLE
Add a small test

### PR DESCRIPTION
**Pull request by mlin**
Adds a small automatic test of assembling a 30kbp region (which takes <<1min). Having this test will help us iterate on some other future adjustment. The test example is cool because it produces a pretty long unitig spanning breakpoints of a complex rearrangement.

Also adds a `.travis.yml` to run this test in Travis CI. After merging you may need to do some [one-time setup](http://docs.travis-ci.com/user/getting-started/) for the repo to get that to work (steps 1 and 2).

In `test.sh`, the invocation of `run-calling` is currently commented out because an htsbox command in it seems to segfault on this example. I haven't tracked down the cause yet. If pressed I'd start by looking at the fact that the reads extend a little bit past the ends of the supplied reference sequence.

### CODE REVIEW

**Comment by ekg** [comment]
:+1: !

**Comment by lh3** [comment]
Thanks a lot!

**Comment by ekg** [comment]
Now you'll just want to set up the integration with travis. You can add a tag to the README as well to show when the build is passing or failing. This is nice as it indicates that the repo is under CI.

**Comment by lh3** [comment]
The segfault is caused by a recent change to abeak. It has not been fixed. CI is also added.

**Comment by lh3** [comment]
Whoops! I meant the bug has just been fixed. "run-calling.pl" now works.

**Pull request merged**
